### ISSUE TITLE
[Help] Host or domain name not found. Name service error for name

### ISSUE THREAD

**Issue by darmawan01** [panubo/docker-postfix#37]
Got this issues:

```
postfix/error[3180]: DF27F16456B: to=<omama@yahoo.co.id>, relay=none, delay=369825, delays=369825/0.15/0/0, dsn=4.4.3, status=deferred (delivery temporarily suspended: Host or domain name not found. Name service error for name=yahoo.co.id type=MX: Host not found, try again)
```

Here is my docker compose:

```
image: panubo/postfix
    environment:
      MAILNAME: domain_name.id 
      MYNETWORKS: "127.0.0.1/32, 10.21.0.0/24"
      USE_TLS: 'no'
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
      - ./mail/spool/postfix:/var/spool/postfix
    restart: always
    ports:
      - "587:25"
```

Anyone can help, what i miss in config ?
