### ISSUE TITLE
SMTPD_USERS not working

### ISSUE THREAD

**Issue by Jono007** [panubo/docker-postfix#48]
Either I am confused about how this is supposed to work, or it is not working.  When I enter a value for 
SMTPD_USERS (e.g. notblank:notblank ), I can still submit emails to postfix without any credentials and they are accepted and relayed. Is that expected behavior? Here are the relevant log entries:

`postfix >> Setting smtpd sasl auth
postfix >> Adding user SASL user: notblank
Jul 19 06:06:22 saslpasswd2: error deleting entry from sasldb: BDB0073 DB_NOTFOUND: No matching key/data pair found
Jul 19 06:06:22 saslpasswd2: error deleting entry from sasldb: BDB0073 DB_NOTFOUND: No matching key/data pair found
Jul 19 06:06:22 saslpasswd2: error deleting entry from sasldb: BDB0073 DB_NOTFOUND: No matching key/data pair found
Jul 19 06:06:22 saslpasswd2: DIGEST-MD5 common mech free
smtp >> Info: "saslpasswd2: error deleting entry from sasldb: BDB0073 DB_NOTFOUND: No matching key/data pair found" can be ignored see https://github.com/cyrusimap/cyrus-sasl/issues/264`

**Comment by macropin** [comment]
From the docs 
> Client authentication is used to authenticate relay clients. Client authentication can be used in conjunction with, or as an alternative to `MYNETWORKS`.

How are you configuring the container?

**Comment by valentinomariotto** [comment]
I used to use this docker compose conf
```
services:
  postfix:
    image: quay.io/panubo/postfix:1.6
    container_name: postfix-relay
    restart: unless-stopped
    env_file: stack.env
    networks:
      - postfix-net
    ports:
      - 25:25 #SMTP
      - 9154:9154 #prometheus exporter
    volumes:
      - ./spool:/var/spool/postfix:rw
      - ./allowed_senders:/etc/postfix/allowed_senders
      
      # hot fixes
      - ./entrypoint-scripts:/etc/entrypoint.d

      # per caricare la chiave dkim come secret, modificare lo script opendkim.conf.sh e rendere opzionali chmod e chown
      - /DOCKER/__certs/DKIM/2025.private:/etc/opendkim/dkim.key
    secrets:
      - exchange-approved-certificate.cer
      - exchange-approved-certificate.key
      - exchange-approved-certificate.ca


secrets:
  exchange-approved-certificate.cer:
    file: /DOCKER/__certs/regalgrid.com.cert
  exchange-approved-certificate.key:
    file: /DOCKER/__certs/regalgrid.com.key
  exchange-approved-certificate.ca:
    file: /DOCKER/__certs/regalgrid.com.ca
#  dkim.regalgrid.com.2025.key:
#    file: ./secrets/DKIM/regalgrid.com/2025.private


networks:
  postfix-net:
    name: postfix-net
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.0.0/16
         gateway: 172.25.0.1
```

With the following env vars
```
MAILNAME='relay.mydomain.com'
MYNETWORKS=....extensive list of networks...
LOGOUTPUT='/dev/stdout'
TZ='Europe/Rome'
POSTFIX_EXPORTER_ENABLED=true

SIZELIMIT=26214400
POSTFIX_ADD_MISSING_HEADERS=no
INET_PROTOCOLS='ipv4'
BOUNCE_ADDRESS='my@address'
HEADER_CHECKS=true
DISABLE_VRFY_COMMAND=yes

SMTP_DESTINATION_CONCURRENCY_LIMIT=3
SMTP_DESTINATION_RATE_DELAY=1s
SMTP_EXTRA_RECIPIENT_LIMIT=200

#default relayhost. Usiamo un indirizzo errato per forzare un errore in caso che non venga trovato il server corretto nella RELAYHOST_MAP
RELAYHOST=[127.0.0.1]:9999
RELAYHOST_AUTH=no
#Sender dependent relayhost map, overrides default RELAYHOST
RELAYHOST_MAP=@extensive list with many domains... 
SENDER_DEPENDENT_RELAYHOST_AUTH=no

#QUESTO NON FUNZIONA. CONTROLLARE AGGIORNAMENTI https://github.com/panubo/docker-postfix/issues/48
#SMTPD_USERS=list of users:passwords

#Impostazioni TLS per smtpd: connessione con i client
USE_TLS=no
TLS_SECURITY_LEVEL=none
TLS_KEY=/run/secrets/exchange-approved-certificate.key
TLS_CRT=/run/secrets/exchange-approved-certificate.cer
TLS_CA=/run/secrets/exchange-approved-certificate.ca

#Impostazioni TLS per smtp: connessione con mailhost (exchange online)
CLIENT_TLS_SECURITY_LEVEL=encrypt
CLIENT_TLS_KEY=/run/secrets/exchange-approved-certificate.key
CLIENT_TLS_CRT=/run/secrets/exchange-approved-certificate.cer
CLIENT_TLS_CA=/run/secrets/exchange-approved-certificate.ca

USE_DKIM=yes
DKIM_KEYFILE=/etc/opendkim/dkim.key
DKIM_DOMAINS=list of domains
DKIM_SELECTOR=2025

# Rate limiting configuration with correct POSTCONF syntax
# Strict relay restrictions - no local delivery
# Per verifiche: always_bcc=test@address
POSTCONF=always_bcc=test@address;smtp_helo_name=relay.mydomain.com;mydestination= ;local_recipient_maps= ;local_transport=error:No local mail delivery;anvil_rate_time_unit=60s;default_process_limit=60;smtpd_client_connection_rate_limit=60;smtpd_client_message_rate_limit=100;smtpd_client_recipient_rate_limit=200;smtpd_client_connection_count_limit=10;smtpd_hard_error_limit=10;smtpd_soft_error_limit=5;smtpd_error_sleep_time=3s;initial_destination_concurrency=2;default_destination_concurrency_limit=3;default_destination_rate_delay=1s;in_flow_delay=2s;maximal_backoff_time=8000s;smtpd_relay_restrictions=permit_mynetworks,reject;smtpd_recipient_restrictions=permit_mynetworks,reject


# Filtro HELO: smtpd_sender_restrictions=reject_unknown_helo_hostname;
CONFIG_RELOADER_ENABLED=true
```

Hotfix script, I don't remember why
```
#!/bin/bash

echo "HOTFIX PATCH: configuring sender_dependent_relayhost_maps=hash:/etc/postfix/relayhost-map"
postconf -e sender_dependent_relayhost_maps="hash:/etc/postfix/relayhost-map"
```


But as I said in the other message, I'm not using Postfix anymore. 
Cheers
